local sncl
sncl = require('../main').sncl
return describe('Testing namespaces', function()
  it('Should recognize XML namespaces', function()
    assert.has_no.errors(function()
      return sncl.parseText('media media_123-456 end')
    end)
    return assert.has_no.errors(function()
      return sncl.parseText('context _context-2._interface-_3 end')
    end)
  end)
  return it('Should error on reserved words', function()
    assert.has_error(function()
      return sncl.parseText('context context end')
    end)
    assert.has_error(function()
      return sncl.parseText('media media end')
    end)
    assert.has_error(function()
      return sncl.parseText('media onBegin end')
    end)
    return assert.has_error(function()
      return sncl.parseText('media media1.context end')
    end)
  end)
end)
